import { ISideBarItem } from "@/@types/sidebar";
import {
  BranchIcon,
  ClipboardIcon,
  HomeIcon,
  NotificationIcon,
  PageIcon,
  PaymentIcon,
  PeopleIcon,
  PersonStarIcon,
  SettingsIcon,
  SpeakerIcon,
  StarIcon,
  TicketIcon,
  UserIcon,
} from "@/svgs";

export const messages = {
  DONT_HAVE_ACCOUNT: "Dont have an account?",
  SIGN_IN: "Sign in",
  SIGN_Up: "Sign Up",
  FORGOT_PASSWORD: "Forgot Password?",
  WELCOME: "Hey \nWelcome to\nMawaqeet",
  GOOD_MORNING: "Good Morning, ",
  PROMOTIONS: "Active Promotions",
  SALES_AMOUNT: "Sales Amount Per Week",
  DAILY_PROGRESS: "Daily Progress",
  MONTHLY_PROGRESS: "Monthly Progress",
  TODAYS_PERFORMANCE: "Todays Performance",
  EXPORT: "Export",
  APPLY_FILTER: "Apply Filter",
  REPORTS: "Reports",
  EMPLOYEES: "Employees",
  ADD_EMPLOYEES: "Add Employees",
  SERVICES: "Services",
  ADD_SERVICES: "Add Services",
  APPOINTMENTS: "Appointments",
  ADD_APPOINTMENTS: "Add Appointments",
  LOYAL_PROGRAM: "Loyal Program",
  Promotions: "Promotions",
  BRANCH: "Branch",
  PROVIDERS: "Providers",
  MANAGE_USERS: "Manage Users",
  SUBSCRIPTION: "Subcription",
  SELECT: "Select",
  COMPLETE: "Complete",
  TOTAL_REQ: "Total Requests",
  CANCELLED: "Cancelled",
  ENTERED_MAN: "Entered Manually",
  EDIT: "Edit",
  DELETE: "Delete",
  TRANSFER: "Transfer",
  ACTIONS: "Actions",
};

export const tableHeader = {
  NAME: "Name",
  SERVICE_NAME: "Service Name",
  JOB_DESC: "Job Description",
  DETAILS: "Details",
  SERVICE_TYPE: "Type of Service",
  BOOKED_TODAY: "Booked Today",
  WORKING_HOURS: "Working Hours",
  RATING: "Rating",
  EMPLOYEE_NUM: "Number of Employees",
  TIME_SLOT: "Time Slot",
  PRICE: "Price",
  BOOKING_ID: "Booking ID",
  CUSTOMER_NAME: "Customer Name",
  CUSTOMER_NUMBER: "Customer Number",
  SERVICES_BOOKED: "Services Booked",
  BRANCH_NAME: "Branch Name",
  PROVIDER_NAME: "Provider Name",
  USER_NAME: "User Name",
  TIME: "Time",
  RANK: "Rank",
  LOYAL_CUSTOMER: "Loyal Customer",
  TOTAL_BOOKING: "Total Bookings",
  MOST_BOOKED: "Most Booked Service",
  LAST_BOOKING: "Last Booking",
  PROMOTION_NAME: "Promotion Name",
  START_DATE: "Start Date",
  END_DATE: "End Date",
  STATUS: "Status",
  CAPACITY: "Capacity",
  AVAILABLE: "Available",
  TYPE: "Type",
  PAID: "Paid",
  RENEWAL: "Renewal",
  DAY_LEFT: "Day Left",
  SUBCRIPTION: "Subscription#",
  LOCATION: "Location",
  DESC: "Description",
  PASSWORD: "Password",
};

export const formConstants = {
  EMAIL_PLACEHOLDER: "Email",
  EMAIL_LABEL: "Email Address",
  EMAIL: "email",
  PASS_PLACEHOLDER: "Password",
  PASS_LABEL: "Your Password",
  PASS: "password",
};

export const sidebarNavigation = (prefix: string): ISideBarItem[] => [
  {
    id: 1,
    name: "Dashboard",
    icon: HomeIcon,
    link: `${prefix}`,
  },
  {
    id: 13,
    name: "Branch",
    icon: BranchIcon,
    link: `${prefix}/branch`,
  },
  {
    id: 2,
    name: "Reports",
    icon: ClipboardIcon,
    link: `${prefix}/reports`,
  },
  {
    id: 3,
    name: "Appointments",
    icon: TicketIcon,
    link: `${prefix}/appointments`,
  },
  {
    id: 4,
    name: "Employees",
    icon: PeopleIcon,
    link: `${prefix}/employees`,
  },
  {
    id: 5,
    name: "Loyal Programs",
    icon: PersonStarIcon,
    link: `${prefix}/loyal-program`,
  },
  {
    id: 6,
    name: "Services",
    icon: PageIcon,
    link: `${prefix}/services`,
  },
  {
    id: 7,
    name: "Promotions",
    icon: SpeakerIcon,
    link: `${prefix}/promotions`,
  },
  {
    id: 8,
    name: "Rating",
    icon: StarIcon,
    link: `${prefix}/rating`,
  },
  {
    id: 9,
    name: "Notifications",
    icon: NotificationIcon,
    link: `${prefix}/notifications`,
  },
];
export const sidebarAdminNavigation: ISideBarItem[] = [
  ...sidebarNavigation("/admin"),
  {
    id: 10,
    name: "Providers",
    icon: NotificationIcon,
    link: "/admin/providers",
  },
  {
    id: 11,
    name: "Manage Users",
    icon: UserIcon,
    link: "/admin/users",
  },
];
export const SettingsNavigation = (prefix: string): ISideBarItem[] => [
  {
    id: 1,
    name: "Subscription",
    icon: PaymentIcon,
    link: `${prefix}/subscription`,
  },
  {
    id: 2,
    name: "Settings",
    icon: SettingsIcon,
    link: `${prefix}/settings`,
  },
];
