import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/Toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<ILayoutProps>) {
  return (
    <html lang="en" dir="ltr">
      <body className={cn(inter.className, "h-screen w-screen ")}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
